# Site settings
course_name: Maestría en Ciencias de la Inteligencia Artificial
course_description: "Primera maestría en Paraguay con dedicación exclusiva, enfocada en en la aplicación y desarrollo de nuevos algoritmos inteligentes"
course_semester: "2025"

baseurl: "/Programa" # the subpath of your site, e.g. /blog/
url: "https://mscia-fiuna.github.io/Programa/" # the base hostname & protocol for your site

schoolname: "Departamento de Electrónica y Mecatrónica"
schoolurl: "https://www.ing.una.py"
twitter_username: ingenieriauna 

address: |
    Facultad de Ingeniería UNA
    San Lorenzo
    Paraguay

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
