# Site
name: 'Maestría en Ciencias de la Inteligencia Artificial
'
description: 'Primera maestría en Paraguay con dedicación exclusiva, enfocada en en la aplicación y desarrollo de nuevos algoritmos inteligentes'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/Programa'
disqus: 'test'
email: 'dstalder@ing.una.py'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Diego:
      name:           Diego
      site:           https://diegostapy.github.io/
      avatar:         /assets/images/avatar1.jpg
      bio:            "I'm currently a full-time researcher at the Engineering Faculty of Asunción National University (FIUNA), where I explore interdisciplinary frontiers"
      email:          dstalder@ing.una.py
      twitter:        https://twitter.com/wowthemesnet

  
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]