# Site settings
course_name: Maestría en Ciencias de la Inteligencia Artificial
course_description: "Primera maestría en Paraguay con dedicación exclusiva, enfocada en en la aplicación y desarrollo de nuevos algoritmos inteligentes"
resumen: "La Facultad de Ingeniería de la Universidad Nacional de Asunción (FIUNA), con el apoyo del Consejo Nacional de Ciencia y Tecnología (CONACYT), anuncia el lanzamiento del Programa de Maestría en Ciencias de la Inteligencia Artificial (MSCIA). Esta propuesta académica tiene como objetivo formar profesionales altamente capacitados en técnicas avanzadas de inteligencia artificial (IA), con un enfoque multidisciplinario e innovador para enfrentar desafíos nacionales e internacionales en áreas estratégicas como agricultura, robótica, sistemas embebidos y biología computacional."

objetives: "El programa busca capacitar a profesionales en:
Técnicas avanzadas de IA, redes neuronales y aprendizaje profundo.
Manejo de grandes volúmenes de datos con metodologías modernas.
Desarrollo de soluciones aplicadas a problemas nacionales en agricultura, medio ambiente y energía.
Formulación y ejecución de proyectos de investigación en IA.
"

perfil: "Los postulantes deberán cumplir con los siguientes requisitos:
Ingenieros/as Recién Egresados de ramas como electrónica, informática, electricidad, electromecánica, mecánica, industrial, civil y egresados de carreras afines con grado de licenciatura, de una universidad paraguaya reconocida por el CONES o de una universidad extranjera con la convalidación correspondiente a las reglamentaciones académicas..
Nivel del inglés para lectura y escritura de artículos científicos.
Dedicación exclusiva de 35 hrs Semanales.
"

course_semester: "2025"

baseurl: "/Programa" # the subpath of your site, e.g. /blog/
url: "https://mscia-fiuna.github.io/Programa/" # the base hostname & protocol for your site

schoolname: "Departamento de Electrónica y Mecatrónica"
schoolurl: "https://www.ing.una.py"
twitter_username: ingenieriauna 

address: |
    Facultad de Ingeniería UNA
    San Lorenzo
    Paraguay

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
